### PR TITLE
add msgbus support

### PR DESCRIPTION
**Pull request by chinchani**
Test coverage is about 85%.  The code itself is very compact, so likely all the corner case panics need to get triggered. Will add them in next commit series.

### CODE REVIEW

**Comment by chinchani** [comment]
CI is failing because I had rabbitmq and nats test code enabled but CI environment doesn't have those running. Disabling those tests in code for now.

**Comment by chinchani** [comment]
internal/messaging/aqmp_msgbus.go | 0% <0%> (ø) |  
-- | -- | --
internal/messaging/nats_msgbus.go | 0% <0%> (ø)

As mentioned above, not much can be done about this unless we rig up external dependencies.

**Comment by rchamarthy** [comment]
@chinchani Can you please break this up into only the interface and the in-memory implementation. We can then make use of this interface with BIRD implementation.

**Comment by chinchani** [comment]
Pls. check now. NATs and RabbitMQ moved into examples/ dir now.

**Pull request merged**
